server:
  port: 8200
spring:
  cloud:
    stream:
      bindings:
        clientToBroker:
          destination: chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: chat-user-messages
          group: topic-chatMessages
          