server:
  port: 8200
spring:
  cloud:
    stream:
      bindings:
        newComments:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
        clientToBroker:
          destination: learning-spring-boot-chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: learning-spring-boot-chat-user-messages
          group: topic-chatMessages
    gateway:
      routes:
        # ================================================
        - id: imagesService
          uri: lb://IMAGES
          predicates:
            - Path=/imageService/**
          filters:
            - RewritePath=/imagesService/(?<segment>.*), /$\{segment}
            - RewritePath=/iamgesService, /
            - SaveSession
        - id: images
          uri: lb://IMAGES
          predicates:
            - Path=/images/**
          filters:
            - SaveSession
        - id: mainCss
          uri: lbL//IMAGES
          predicates:
            - Path=/main.css
          filters:
            - SaveSession
        - id: commentsService
          uri: lb://IMAGES
          predicates:
            -Path=/comments/**
            filters:
              - SaveSession
          